### ISSUE TITLE
Filtering does not work on the operator namespace

### ISSUE THREAD

**Issue by pebrc** [elastic/eck-diagnostics#138]
Filtering introduced in #132 does not filter in the operator namespace. The motivation for this is that we want to extract all resources from this namespace to extract as much information as possible that pertains to the operator. 

However this becomes a problem when users deploy workloads into the operator namespace (something that is discouraged but not explicitly forbidden, we need to call this out more explicitly in  documentation). 

To remedy this problem we should rework the way we treat the operator namespace: 
* we should respect any filters defined by the user in the operator namespace
* we should still extract operator related resources from the operator namespace but be more targeted e.g. try to identify the operator Pod and extract its logs
* we need to distinguish between different deployment modes of the operator (there is some initial code around this already in the tool) to cover OLM installations as well as manual YAML  manifest based installations and Helm based installs.

**Comment by thbkrkr** [comment]
I looked at #153 and there is one thing to clear up. Consider the scenario where the operator and resources are deployed in a single `elastic` namespace.

Do we expect the user to make the `elastic` namespace explicit as being an operator namespace and a resources namespace?

`eck-diagnostic -o elastic -r elastic`

or is it enough for them to specify the former?

`eck-diagnostic -o elastic`

**Comment by thbkrkr** [comment]
I forget that `--resources-namespaces` is required, so `eck-diagnostic -o elastic` is not allowed.
