### ISSUE TITLE
Utilize elastic-agent diagnostic command

### ISSUE THREAD

**Issue by david-kow** [elastic/eck-diagnostics#69]
We can use elastic-agent native [diagnostic command ](https://www.elastic.co/guide/en/fleet/8.0/elastic-agent-cmd-options.html#elastic-agent-diagnostics-command) to get much better insight into Agent configuration as well as enable product team to investigate Agent related issues better.

**Comment by pebrc** [comment]
If I understand correctly how the agent diagnostic command works then this is going to be a bit tricky. IIUC this has be run inside the container with the same configuration as the actual production agent process (so not remote execution or extraction via API as we have it with Elasticsearch and Kibana). That means we could `exec` into the running container an run the diagnostics there. But I wonder if that might lead to problems in production scenarios where the agent runs with limited resources. We have to test 
* if the diagnostics can push the agent above its resource limits leading to restart
* where we can store and retrieve the archive from (we typically have a `hostPath` volume but can we rely on that being present? Do we have it in Fleet mode?)

**Comment by pebrc** [comment]
It looks like the command was introduced in 7.16 https://www.elastic.co/guide/en/fleet/7.16/release-notes-7.16.0.html
