### ISSUE TITLE
OpenID Connect via Dex causes diag to fail

### ISSUE THREAD

**Issue by damianpfister** [elastic/eck-diagnostics#75]
Similar to https://github.com/elastic/eck-diagnostics/issues/61, when using [dex](https://github.com/dexidp/dex) for OIDC integration, the following error is presented:
```
Error: failed to retrieve OpenAPI schema: no openapi getter
```

Are there any ways around this perhaps using https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth/oidc or would we need an ER to add this to the eck-diag tool?

**Comment by pebrc** [comment]
I have not been able to reproduce this setup yet. But my hunch would be that `kubelogin` might be a possible workaround to  login to the cluster and generate a kubeconfig that can be shared and used by `eck-diagnostics` similar to https://github.com/elastic/eck-diagnostics/issues/61#issuecomment-1012988218
