### ISSUE TITLE
[Discussion] Make user be able to choose node roles / data tiers when taking ECK diag

### ISSUE THREAD

**Issue by kunisen** [elastic/eck-diagnostics#93]
If user has many pods in the ECK operator/resource namespace, it may take long time to run ECK diag.
i.e. 200+ pods can take 35 min to run ECK diag by default.

It might be great to provide an ability for user to choose which node role (master/data/etc) or data tier (hot/warm) to take.

cc @jstrassb @eedugon

**Comment by pebrc** [comment]
Duplicate of #81

**Comment by kunisen** [comment]
Thanks @pebrc 
Yeah it looks like the same from a high level, but maybe in details, this one has more clear requirements.
Anyway I am fine with closing this one as long as it's on the board :)
